name: PHP Client - Dependency Test

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Init project
      run: |
        php composer.phar create-project composer/semver

    - name: Install dependencies
      run: |
        composer require labs64/netlicensingclient-php
        composer install --prefer-dist --no-progress --no-suggest
