name: PHP Client - Dependency Test

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Init project
      run: |
        composer create-project composer/semver netlicensing-php-dependency

    - name: Install dependencies
      run: |
        composer require labs64/netlicensingclient-php
        composer install --prefer-dist --no-progress --no-suggest
